apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone
  labels:
    app: reddit-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
      - name: reddit-clone
        image: zeyadabdelghanyy/reddit-clone:13
        command: ["/bin/sh", "-c"]
        args:
          - "npm install -g firebase-tools && npm start"
        ports:
        - containerPort: 3000
        # إضافة لضمان استقرار الـ Pod
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer
  selector:
    app: reddit-clone
  ports:
  - port: 80
    targetPort: 3000